version: "3.3"
services:
  app:
    image: skeleton-java
    network_mode: host
    container_name: skeleton-java
    volumes:
      - $PWD:/app
      - $HOME/.m2:/root/.m2
    user: "0:0"
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8080:8080"
    restart: always